### ISSUE TITLE
Questions about the experimental setup on NASbench101

### ISSUE THREAD

**Issue by December-boy** [SLDGroup/ZiCo#1]
Thanks for this great work!
I have some questions about the experimental setup dan results on NASbench101 used in this paper.
1. As for the experiment on NASbench101 mentioned in the article, I am curious whether it includes all 423,624 models in NASbench101. The visualizations provided in the paperdo not seem to include all 423,624 models:
![image](https://user-images.githubusercontent.com/23350028/231040642-d99cfe0f-f477-4c1e-a1b0-0c278e8002e1.png)
2. The correlation results of some existing proxies are also different from those of other papers.
Please help me to figure out these questions, thank you!

**Comment by LiGuihong** [comment]
Hi there,

1. The correlation scores are computed based on all 423K models for NASbench-101. We didn't plot all these 423K samples in the figures since it will make the figure too big. Hence, we randomly sample 500 samples shown in this figure. 
2. As for the difference, there may be some implementation details that are different from other papers.

Best,
Guihong

**Comment by December-boy** [comment]
Get it! Thank you!
